name: Continuous Integration

# Trigger this workflow when we push or pull request
on: [push, pull_request]

jobs:
  build:
    # Set the environment that we are going to use to ubuntu the latest version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set the jdk that we are going to use to java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Run spotbugs with gradle
      - name: Run tests with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew --stacktrace --info spotbugsMain
      # Upload the reports that Spotbugs created on Git
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: 'Spotbugs Reports'
          path: ./build/reports/